import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync, cpSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawn, spawnSync } from 'node:child_process';
import { once } from 'node:events';
import { request } from 'node:http';
import { codexCommand } from '../../scripts/lib/codex-command.mjs';
import { readEvents, appendEvent, reduceEvents, normalizeCodex } from '../../scripts/lib/loop-events.mjs';
const root=resolve(dirname(fileURLToPath(import.meta.url)),'../..');
const event=(extra={})=>({engine:'codex',role:'main',status:'running',runId:'one',summary:'실제 기록',...extra});
test('partial/corrupt JSONL is isolated, completed records survive',()=>{const r=mkdtempSync(join(tmpdir(),'loop-'));try{appendEvent(r,event());writeFileSync(join(r,'loop/.runtime/events.jsonl'),readFileSync(join(r,'loop/.runtime/events.jsonl'))+'bad\n'+JSON.stringify(event({status:'done'})));const result=readEvents(r);assert.equal(result.events.length,1);assert.equal(result.invalid,1);}finally{rmSync(r,{recursive:true,force:true});}});
test('new run resets stale gates and engines remain independent',()=>{const events=[event({role:'reviewer',checkpoint:'before-done',status:'done'}),event({test:{name:'unit',status:'passed'}}),event({engine:'claude',runId:'claude',status:'done'}),event({runId:'two',status:'failed'})];const s=reduceEvents(events,'codex');assert.equal(s.runId,'two');assert.equal(s.session,'failed');assert.equal(s.tests.length,0);assert.deepEqual(s.checkpoints,{});assert.equal(reduceEvents(events,'claude').session,'done');});
test('duplicate CLI item is not counted twice; usage is latest turn only',()=>{const e=event({eventId:'same',usage:{input_tokens:100,output_tokens:20}});const s=reduceEvents([e,e,event({usage:{input_tokens:12,output_tokens:3}})],'codex');assert.equal(s.usage.input_tokens,12);assert.equal(s.agents[0].status,'running');});
test('native CLI events never fabricate test PASS or expose outputs',()=>{const e=normalizeCodex({type:'item.completed',item:{id:'x',type:'command_execution',command:'secret-cli --token PRIVATE',aggregated_output:'PRIVATE',exit_code:1}},'one','model');assert.equal(e.status,'failed');assert.ok(!JSON.stringify(e).includes('PRIVATE'));assert.equal(reduceEvents([e],'codex').tests.length,0);const turn=normalizeCodex({type:'turn.completed',usage:{input_tokens:3,output_tokens:1}},'one','model');assert.equal(turn.status,'running');assert.equal(normalizeCodex({type:'future.event'},'one','model'),null);});
test('invalid checkpoints, role, negative usage and invalid tests rejected',()=>{const r=mkdtempSync(join(tmpdir(),'loop-'));try{for(const extra of [{role:'root'},{checkpoint:'fake'},{usage:{input_tokens:-1}},{test:{name:'unit',status:'done'}}])assert.throws(()=>appendEvent(r,event(extra)));}finally{rmSync(r,{recursive:true,force:true});}});
test('dashboard serves empty real records, demo separately, rejects mutations and paths',async()=>{const fixture=mkdtempSync(join(tmpdir(),'dashboard-fixture-'));cpSync(join(root,'scripts'),join(fixture,'scripts'),{recursive:true});cpSync(join(root,'tools'),join(fixture,'tools'),{recursive:true});const child=spawn(process.execPath,[join(fixture,'scripts/agent-dashboard.mjs'),'--port','44317'],{cwd:fixture});try{await once(child.stdout,'data');const base='http://127.0.0.1:44317';const state=await(await fetch(base+'/api/state')).json();assert.equal(state.demo,false);assert.equal(state.engines[0].runId,null);assert.equal((await fetch(base+'/',{method:'POST'})).status,405);assert.equal((await fetch(base+'/.codex/config.toml')).status,404);const rejected=await new Promise((resolve,reject)=>{const req=request(base+'/api/state',{headers:{Host:'evil.example'}},res=>{res.resume();resolve(res.statusCode);});req.on('error',reject);req.end();});assert.equal(rejected,403);const malformed=await new Promise((resolve,reject)=>{const req=request({hostname:'127.0.0.1',port:44317,path:'//[',headers:{Host:'127.0.0.1:44317'}},res=>{res.resume();resolve(res.statusCode);});req.on('error',reject);req.end();});assert.equal(malformed,400);assert.equal((await fetch(base+'/')).status,200);assert.ok((await(await fetch(base+'/')).text()).includes('AGENT LOOP'));}finally{child.kill();await once(child,'exit');rmSync(fixture,{recursive:true,force:true});}});
test('Codex check/dry-run never execute session; run normalizes real output; guards reject',async()=>{
 const temp=mkdtempSync(join(tmpdir(),'codex-launch-'));const bin=join(temp,'bin');mkdirSync(bin);
 cpSync(join(root,'scripts'),join(temp,'scripts'),{recursive:true});cpSync(join(root,'tools'),join(temp,'tools'),{recursive:true});cpSync(join(root,'.codex'),join(temp,'.codex'),{recursive:true});cpSync(join(root,'loop/codex-prompt.md'),join(temp,'loop/codex-prompt.md'),{recursive:true});
 const expected=JSON.parse(readFileSync(join(temp,'tools/agent-dashboard/project.json'))).repository;
 writeFileSync(join(bin,'git'),`#!/usr/bin/env node\nconsole.log(process.argv.includes('--show-current')?(process.env.TEST_BRANCH||'work/loop'):'https://github.com/'+(process.env.TEST_ORIGIN||'${expected}')+'.git');\n`,{mode:0o755});
 writeFileSync(join(bin,'codex'),`#!/usr/bin/env node\nconst fs=require('fs');if(process.argv.includes('--version'))console.log('codex 1.0.0');else if(process.argv.includes('--help'))console.log('--json --sandbox --model');else{if(process.env.TEST_STREAM==='error'){console.log(JSON.stringify({type:'turn.failed'}));process.exit(0);}if(process.env.TEST_STREAM==='invalid'){console.log('bad JSON');process.exit(0);}fs.writeFileSync('called.json',JSON.stringify(process.argv));process.stdin.resume();process.stdin.on('end',()=>{console.log(JSON.stringify({type:'turn.completed',usage:{input_tokens:8,output_tokens:2}}));});}\n`,{mode:0o755});
 const env={...process.env,PATH:bin+':'+process.env.PATH};const call=(arg,extra={})=>spawnSync(process.execPath,['scripts/codex-loop.mjs',arg],{cwd:temp,env:{...env,...extra},encoding:'utf8',timeout:10000});
 try{for(const mode of ['--check','--dry-run']){const r=call(mode);assert.equal(r.status,0,r.stderr);assert.equal(existsSync(join(temp,'called.json')),false);}const run=call('--run');assert.equal(run.status,0,run.stderr);const args=JSON.parse(readFileSync(join(temp,'called.json')));assert.ok(args.includes('--json'));assert.equal(args[args.indexOf('--sandbox')+1],'workspace-write');assert.equal(args.at(-1),'-');assert.equal(existsSync(join(temp,'loop/.runtime/codex.lock')),false);const s=reduceEvents(readEvents(temp).events,'codex');assert.equal(s.session,'done');assert.equal(s.tests.length,0);assert.equal(s.usage.input_tokens,8);assert.equal(call('--run',{TEST_STREAM:'error'}).status,1);assert.equal(call('--run',{TEST_STREAM:'invalid'}).status,1);assert.equal(existsSync(join(temp,'loop/.runtime/codex.lock')),false);assert.equal(call('--run',{TEST_BRANCH:'main'}).status,1);assert.equal(call('--run',{TEST_BRANCH:'' ,TEST_ORIGIN:'jjsjb88-alt/9-baseball'}).status,1);writeFileSync(join(temp,'loop/.runtime/codex.lock'),'');const before=readEvents(temp).events.length;assert.equal(call('--run').status,1);assert.equal(readEvents(temp).events.length,before);rmSync(join(temp,'loop/.runtime/codex.lock'));rmSync(join(temp,'loop/.runtime/events.jsonl'));mkdirSync(join(temp,'loop/.runtime/events.jsonl'));assert.equal(call('--run').status,1);assert.equal(existsSync(join(temp,'loop/.runtime/codex.lock')),false);}finally{rmSync(temp,{recursive:true,force:true});}
});

test('Windows npm JS shim is invoked without command shell',()=>{const temp=mkdtempSync(join(tmpdir(),'windows-codex-'));try{const file=join(temp,'node_modules/@openai/codex/bin/codex.js');mkdirSync(dirname(file),{recursive:true});writeFileSync(file,'');const c=codexCommand('win32',temp);assert.equal(c.file,process.execPath);assert.deepEqual(c.prefix,[file]);assert.deepEqual(codexCommand('linux'),{file:'codex',prefix:[]});}finally{rmSync(temp,{recursive:true,force:true});}});

test('late older-run reports do not resurrect prior session',()=>{const s=reduceEvents([event({runId:'old'}),event({runId:'new'}),event({role:'reviewer',status:'done',runId:'old'})],'codex');assert.equal(s.runId,'new');assert.equal(s.agents.find(a=>a.role==='reviewer').status,'waiting');});
test('in-progress command with null exit code is not a failure',()=>{const e=normalizeCodex({type:'item.started',item:{id:'pending',type:'command_execution',status:'in_progress',exit_code:null}},'one','model');assert.equal(e.status,'running');});
